version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: sh -c "npm install &&
                  npm run start:debug"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: system
    ports:
      - 5432:5432
    volumes:
      - ./conf/pg-data:/var/lib/postgresql/data